export const listBagian = [
    "Keuangan & Umum",
    "Keamanan",
    "Tanaman",
    "TMA",
    "Quality Assurance",
    "Instalasi - Kantor Instalasi",
    "Instalasi - ST. Besali",
    "Instalasi - ST. Bangunan",
    "Instalasi - ST. Gilingan",
    "Instalasi - ST. Ketel",
    "Instalasi - ST. Listrik",
    "Instalasi - ST. Instrumentasi",
    "Instalasi - ST. Kendaraan",
    "Pengolahan - Kantor Pengolahan",
    "Pengolahan - ST. Masakan",
    "Pengolahan - ST. Pemurnian",
    "Pengolahan - ST. Penguapan",
    "Pengolahan - ST. Puteran",
    "Pengolahan - ST. Limbah",
    "Pengolahan - ST. Pengemasan",
    "Lain-lain",
  ];